### ISSUE TITLE
pattern/innersource-portal-hygiene

### ISSUE THREAD

**Issue by dineshdh** [InnerSourceCommons/InnerSourcePatterns#118]
## Title

InnerSource Portal - Hygiene

## Patlet

Based off the [InnerSource portal](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/innersource-portal.md) pattern.

Allow generation of an official badge for projects intending to be recognised as InnerSource project within your company.

This will help users distiguishing InnerSource projects which strive to adhere to InnerSourcing principals from repos that have been made public due to neglegence or other reasons, plus the badge serves as additional marketing for the InnerSource intiative at your company.

## Problem

- Users don't have a mechanism of distiguishing InnerSource projects which strive to adhere to InnerSourcing principals from repos that have been made public due to neglegence or other reasons.
- Unmaintained or stale InnerSource projects clutter the portal and make it difficult for people to discover active projects, and diminishes the value on the InnerSource portal

## Context

Large organisation with lots of public repos, not all necessarily meeting the desired innerSource project standard.

## Forces

- Mix of managed and unmanged projects makes it difficult to figure out what needs to be in the InnerSource portal
- Repos are made public when they really shouldn't be
- Repos become stale and never get cleaned up

## Sketch
Sorry about the picture :(
<img src="https://lh3.googleusercontent.com/rE08a2S-RPJ76hT2VZe4TcOZG1YG0-SaG29O6fLEc5DovNwOViVX7C6ZT66JdH0GYsCg3neHS3En_FkQzKowzyO6Ev_NSr7d_I5wmdyt635-FPbMZBOTOjBb3g_aVrlq4LSiA7Wwxw=w2230-h1672-no" />

### Register your InnerSource project

In your InnerSource portal allow registering your project as an InnerSource project. This is a super simple an intuitive webform that only requires you to enter your repos url.

Once the url is entered some basic checks will be carried out against your repo based on some very basic standards required for entry into the InnerSource portal. These checks include:

- Access to the repo
- Description for repo is set
- Topic labels exists
- Code owners file exists and populated
- Readme file exists
- Pull request template file exists
- Issue template file exists
- Contributing guidelines file exists

Once all checks have passed the InnerSource portal will generate your very own InnerSource badge, which is basically am image with a random filename. Note this badge is specific to the repo that was being registered. In the background the repo name, badge filename and badge expiry date is stored.

The last step is for users update there repos README.md file to include the badge. This will then allow the InnerSource portal to discover the project and will automatically include it in the portal.

### InnerSource portal batch jobs

- Update InnerSource portal projects.  
Query InnerSource projects have a non expired badge. Display these in the portal
- Remove expired badges.  
Query InnerSource projects which have an expired badge. Delete badge file causing the badge to not appear in the repos rendered README anymore.
- Notify projects approaching expiry.  
Query InnserSource projects which have a badge close to expiration. Send a notification to the InnerSource projects code owners, publish an issue to the repo, publish a message in the InserSource channel on Teams. This should be ample warning to go update the badge.

## Resulting Context

The autom managed InnerSource portal and badge system has ensured that the InnerSource portal only displays active projects and as result contains less clutter, thus increasing the credibility of the portal and InnerSource project initiative itself. The badges in the repos itself allow people to quickly distinguish an innerSource project from a standard public repo.

## Author(s)

- Dinesh Dharmawardena

**Comment by rrrutledge** [comment]
This is cool, @dineshdh.  I think it would be a good idea to open a pull request to the `InnerSourcePatterns` repository so that we can all discuss there.  Looking forward to it!

**Comment by dineshdh** [comment]
PR created as suggested by @rrrutledge 
https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/120

**Comment by spier** [comment]
@dineshdh I just found this PR again, and was wondering if you have made further experiences with this "hygiene approach" in your InnerSource practice?
