### ISSUE TITLE
Pattern Maturity in patterns does not match defined pattern-states nomenclature

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#128]
I am making this assumption:

The `#Status` defined in [pattern-template.md](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/pattern-template.md) is meant to be one of the defined [pattern-states](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/pattern-states.md).

Assuming that the above is true:

When reading some of the existing patterns I found that some of them don't have a `#Status` set at all, while others have one but they don't match the defined [pattern-states](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/pattern-states.md).

Would it be worth fixing this, so that all patterns specify what their Pattern Maturity is, following the [pattern-states](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/pattern-states.md).

For reference some examples of patterns and their `#Status`:

```
$ egrep -A2 "Status|State\s*$" InnerSourcePatterns/*.md

InnerSourcePatterns/30-day-warranty.md:# State
InnerSourcePatterns/30-day-warranty.md-Drafted at the 2017 Spring InnerSource Summit; reviewed 18 July 2017.
--
InnerSourcePatterns/common-requirements.md:## Status
InnerSourcePatterns/common-requirements.md-Shepherded pattern
--
InnerSourcePatterns/contracted-contributor.md:## Status
InnerSourcePatterns/contracted-contributor.md-_Proven Pattern_
--
InnerSourcePatterns/dedicated-community-leader.md:## Status
InnerSourcePatterns/dedicated-community-leader.md-_Reviewed Pattern_
--
InnerSourcePatterns/discover-your-innersource.md:## Status
InnerSourcePatterns/discover-your-innersource.md-Brainstormed pattern idea in progress
--
InnerSourcePatterns/improve-findability.md:## Status
InnerSourcePatterns/improve-findability.md-Brainstormed pattern idea reviewed 2017-03-11.
--
InnerSourcePatterns/introducing-metrics-in-innersource.md:# State
InnerSourcePatterns/introducing-metrics-in-innersource.md-Early Idea
--
InnerSourcePatterns/junkyard-styled-innersourcing.md:## Status
InnerSourcePatterns/junkyard-styled-innersourcing.md-Brainstormed pattern idea in progress
--
InnerSourcePatterns/modular-code.md:**Status:**
InnerSourcePatterns/modular-code.md-Donut
--
InnerSourcePatterns/review-committee.md:## Status
InnerSourcePatterns/review-committee.md-_Finalized and Reviewed_ as of 8/31/17.
--
InnerSourcePatterns/start-as-experiment.md:# Status
InnerSourcePatterns/start-as-experiment.md-Proven Pattern
```

**Comment by rrrutledge** [comment]
Agree.  Great point.

**Comment by spier** [comment]
@rrrutledge if you think that would be ok, then I can send a PR that takes the **Status** that I see for each pattern in the list in https://github.com/InnerSourceCommons/InnerSourcePatterns#list-of-patterns and update all Pattern files to contain their respective status.

However if I do that I will be touching a lot of pattern files. Therefore we would have to get that PR merged fairly quickly back into master, as it will otherwise collided with any other work anybody might be doing on the pattern files.

**Comment by rrrutledge** [comment]
I think that we could get that turned around before appreciable change in the patterns file that it targets.

**Comment by spier** [comment]
Cool. Then I will start working on that. Feel free to assign the issue to me if you like.

**Comment by rrrutledge** [comment]
Done
