### ISSUE TITLE
Some markdown files are not linked from README.md

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#135]
When comparing the number of markdown files in this repo, to what is linked from `README.md`, I found that the numbers are different:

```
$ ll *.md | wc -l
      19

$ ack "\([^/]+.md\)" README.md | wc -l
      15
```

So we have 19 markdown files, but only 15 files linked in README.md.

I will send a PR to investigate where the difference comes from.

**Comment by rrrutledge** [comment]
Sounds great.

**Comment by spier** [comment]
Done. Closing this issue.
