### ISSUE TITLE
Turn "InnerSource License" from DB Systel into a pattern

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#138]
DB Systel created their own InnerSource License, see [DB Inner Source License](https://github.com/dbsystel/open-source-policies/blob/master/DB-Inner-Source-License.md) (in German). 

They used the EUPL, as that offered an open-source-like starting point, and then worked out the constraints and additional rules required in their specific company context.

I would like to turn this into a pattern, mostly to learn how they did it, and also how the pattern syntax "works in practise" :)

**Comment by spier** [comment]
I have started to work with DB Systel on this. So far the collaboration is happening in a Google Doc as that offers faster suggestion/review features that markdown.

I hope to be able to convert this gDoc to markdown within the next weeks, and push it to this repo.

**Comment by maxcapraro** [comment]
Would you like to share the Doc in this issue as well? I'd love to take a sneak peak / maybe comment some thoughts.

**Comment by spier** [comment]
Even though I am all for sharing, in this particular instance I don't want to share the doc.

Here my reasoning:
The doc is roughly the "interview transcript" between Cornelius and myself, and I want to turn that into markdown as quickly as possible, so that everybody here can see it. The longer we keep it in gDoc the higher the chances that it will get lost. And adding more comments now would increase that risk, I fear.

But I promise to push a PR with the markdown as soon as Cornelius reviews the gDoc and gives me the thumbs up. 👍

**Comment by maxcapraro** [comment]
This really makes sense :) Don't feel rushed!

**Comment by lenucksi** [comment]
We merged #147 do we need anything else to close this or can we close this? @spier might know.

**Comment by spier** [comment]
Yeah, we just forgot this issue. This can be closed.
