### ISSUE TITLE
Auto-Generate the Mindmap on .md-source changes

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourcePatterns#162]
#156 is great stuff, we just need to remember to add a GitHub Action to regenerate the SVG / HTML / rendered products once the .md changes and make a checklist item for PRs to update the .md once new things come in to keep everything fresh. 

_Originally posted by @lenucksi in https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/156#issuecomment-624834371_

**Comment by spier** [comment]
When you say mindmap, are you referring to `IS.md` and `IS.html`?

What I am missing from `IS.md` as well is an explanation of what it is. e.g. if any reader of the IS Patterns finds this file, how would they know what it is?

**Comment by lenucksi** [comment]
> When you say mindmap, are you referring to `IS.md` and `IS.html`?

With `mindmap` I'd refer to the rendered artifact(s), i.e. the SVG or the SVG embedded in a HTML file.
`mindmap source` is the underlying MD file.

Sorry for having an issue that is still a bit raw - it's generated from a PR comment to be dealt with later.
> 
> What I am missing from `IS.md` as well is an explanation of what it is. e.g. if any reader of the IS Patterns finds this file, how would they know what it is?

I would hope that we have the mindmap embedded an a larger production (e.g. the pattern catalogue or book at some point) that has additional details explaining it.

**Comment by spier** [comment]
FYI documentation and files related to the mindmap are now in:
https://github.com/InnerSourceCommons/InnerSourcePatterns/tree/master/pattern-categorization

**Comment by spier** [comment]
I asked a question on the [markmap repo](https://github.com/gera2ld/markmap/issues/66) related to this. 

While we could generate the input file (markdown) automatically, markmap doesn't have an option to turn that into a static file that we can embed in our book at https://patterns.innersourcecommons.org.

**Comment by spier** [comment]
This particular issue has been implemented in #348
