### ISSUE TITLE
Broken link to "Donut 8: Not Invented Here"

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#165]
README.md contains a link to a wiki page that does not exist (anymore).

```
[Donut 8: Not Invented Here](https://github.com/InnerSourceCommons/innersourcecommons.org/wiki/Donut-8:-Not-invented-here)
```

I have not checked the history of https://github.com/InnerSourceCommons/innersourcecommons.org/wiki yet but I would suspect that it was deleted at some point?

@lenucksi any idea about this one?

**Comment by lenucksi** [comment]
Looking at the commits for the wiki that are supposed to be in https://github.com/InnerSourceCommons/innersourcecommons.org-wiki/commits/master I couldn't find any commits pointing to deletion of a page of that name in my first short research. 
Leaving this open for further research.

**Comment by spier** [comment]
@lenucksi in the interest of cleaning up our repo, I suggest that we give up on this one. I have removed the reference to this Donut Pattern in https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/188/commits/0869b3b08a88f152bdc03082e1af413c0660790d

I say let's close this issue. If anybody every comes across this problem again, they can always create a new Donut.

**Comment by lenucksi** [comment]
Since we have not been able to retrieve the missing :doughnut: we're closing this right now and removed the pattern from the index as @spier mentioned (thanks!). 
If the creator of the :doughnut: finds this: Please bring it up again if you think it should be brought up.
