### ISSUE TITLE
Design `Advanced Style Guide`

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourcePatterns#169]
We should develop an initial version of an advanced style guide. This is relevant for the maturity level `4: established` proposed by #155.

(Edited by @maxcapraro)

**Comment by spier** [comment]
@maxcapraro after dropping level 4, we can close this issue here, or not?

**Comment by spier** [comment]
Closing this issue as we changed the requirements for our maturity levels. Level 4 does not exist any more i.e. an _Advanced Style Guide_ is no longer needed.
