### ISSUE TITLE
Pattern idea: Use build/package manager to promote discoverability and reusability

### ISSUE THREAD

**Issue by gruetter** [InnerSourceCommons/InnerSourcePatterns#17]

**Comment by spier** [comment]
Playing devils advocate here :)
Given that this issue did not see any traction in 3 years, maybe we close it and wait for it to be reinvented if it is important?

**Comment by rrrutledge** [comment]
That works.

**Comment by spier** [comment]
Not enough context in this issue to create a pattern from it. Will close it as **Stale**.

Also if this is truly an InnerSource pattern, I would expect it to be discovered one day by somebody else again :)
