### ISSUE TITLE
Design `Glossary`

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourcePatterns#170]
We should develop an initial version of a glossary - also containing working group terminology we want to use. It's main focus should be on InnerSource-specific terminology, though. This glossary will be used to validate patterns against the requirements of [Level 3 - Validated](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/contributor-handbook.md#requirements-level-3---validated). 

(Edited by @maxcapraro)

**Comment by maxcapraro** [comment]
I want to point out that this is not only relevant in the light of #150, but needed independently of it.

**Comment by lenucksi** [comment]
Collected some review / issue links that mention the need for a glossary or possible entries (will amend once I find more):

https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/46/files#r168488949

**Comment by spier** [comment]
A first version of a glossary is now available in https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/meta/glossary.md.

I suggest that we improve the glossary incrementally, as we review further patterns, rather than keeping this open as a separate issue.
