### ISSUE TITLE
Design `Basic style guide`

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourcePatterns#171]
We should develop an initial version of a basic style guide, which will be used to validate patterns against the requirements of [Level 2 - Structured](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/contributor-handbook.md#requirements-level-2---structured). This is a follow up on PR #155. 

(Edited by @maxcapraro)

**Comment by spier** [comment]
A Basic style guide is now available at 
https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/meta/pattern-style-guide.md
