### ISSUE TITLE
Pattern idea: Increase inter-team engagement with Internal RFCs

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#174]
[Requests for Comments](https://en.wikipedia.org/wiki/Request_for_Comments) (RFCs) are a well known concept in the Open Source world. At my company similar concepts start to evolve that go by different slightly different names, but at the end of the day they are RFCs that are only meant for company-internal communication.

I did some googling and found that others are describing similar things. The best article I found so far is [Scaling Engineering Teams via Writing Things Down and Sharing - aka RFCs](https://blog.pragmaticengineer.com/scaling-engineering-teams-via-writing-things-down-rfcs/).

In the article the author, Gergely Orosz from Uber, explains their internal RFC process, and ends with:

> So is this process unique to Uber? Far from it. Larger tech companies, like Google, Facebook, Microsoft or Amazon all came up with something that resembles some level of RFC process. 

This makes me hopeful that we could find enough Known Instances of this approach at other companies, to turn this into a proven pattern.

_"How those this relate to InnerSource"_ you may ask:

My claim is that a process like this helps you to involve the internal Engineering community within your growing organization at an early phase of major projects or architecture decisions.
 
This will eventually lead to a higher degree of interaction between teams, and with that also to more InnerSource contributions of any sort. At the most basic level, any RFC/Architecture discussion that is happening between teams is already an InnerSource contribution, isn't it?

So what do you say? Is this worth turning into a pattern?

I looked through the existing patterns and did not find one like this.

## Appendix 

Other names for the same thing:

* Architecture Decision Records
* Architecture Design Records
* Design Decision Records
* Internal RFCs

**Comment by spier** [comment]
The Open Decision Framework also seems related to this: https://github.com/red-hat-people-team/open-decision-framework/blob/master/ODF-community.md

**Comment by jpatrao** [comment]
RFCs can be sent out for projects that aren't necessarily inner source projects but where we need to 1) solicit input from the users e.g. users of an existing or potential users of a new API or library 2) solicit guidance from technical experts in other parts of the company 3) project openness and transparency 4) project a sense of urgency because deadlines for comments are typically communicated in RFCs.

From the IS perspective, a useful pattern could be how trusted committers or project maintainers could adopt this practice before embarking on refactoring, re-writes. This pattern would look at various [aspects](https://github.com/inasafe/inasafe/wiki/How-to-write-an-RFC) of RFCs  and suggest best practices within an IS context. Here are two examples: a) Approval of an RFC should include approval (unanimous or majority) of trusted committers of the project, b) RFCs should be sent out only after getting some support from the trusted committers/maintainers else it is doomed to fail and the creation of the RFC is wasted effort.

**Comment by spier** [comment]
Thanks for the insights @jpatrao.

I agree, company-internal RFCs are not only beneficial for InnerSource projects, but can also be a helpful tool for projects that don't usually see InnerSource contributions, such like what you are describing above. 

As an aside, I would argue that "guidance from technical experts in other parts of the company" in point (2) above could be considered an excellent example of an InnerSource contributions. Everything counts, not just code :) 

So hopefully we can catch the essence of this as a pattern for the InnerSource scenario. Your idea with evaluating the different parts of an RFC with regards to their relevant to InnerSource sounds interesting too.

Btw how did you find the link to https://github.com/inasafe/inasafe/wiki/How-to-write-an-RFC?

**Comment by jpatrao** [comment]
Yes, agreed. Everything counts, not just code. 

I just googled "purpose of writing out an RFC" to find out all the [aspects](https://github.com/inasafe/inasafe/wiki/How-to-write-an-RFC) of it. It came up in the first link.

**Comment by stephegn** [comment]
I just wanted to share the presentation which first really opened my eyes to how these sorts of techniques can be used internally within organisations

https://www.infoq.com/presentations/avvo-continuous-improvement/

It doesn't talk about innersource specifically but it talks about making decisions visible and getting collaboration when making changes. 

It also points out the importance of using data to drive decisions which in my experience RFCs and ADRs really encourage.

**Comment by spier** [comment]
See this [conversation in Slack](https://innersourcecommons.slack.com/archives/C2EFRTS6A/p1589310515237000) about this topic.

**Comment by lenucksi** [comment]
@tsadler1988 might be interested too :)
Thanks for writing this up!

**Comment by lenucksi** [comment]
We've now merged the write-up as #204. Should we close this ticket accordingly?

**Comment by spier** [comment]
Yes, I am closing this. We will improve this pattern further but for that we don't need this issue, which was mostly a reminder to write the first version :)

Thanks for catching this.
