### ISSUE TITLE
Definition of an Open Source or Inner Source Project

### ISSUE THREAD

**Issue by chtompki** [InnerSourceCommons/InnerSourcePatterns#181]
I'm working with @MaineC on a paper about open source ideas, and need a citable resource for the work. So, I'm going to make a contribution in [/patterns/1-initial](https://github.com/InnerSourceCommons/InnerSourcePatterns/tree/master/patterns/1-initial) about what I think the minimum resources of an open source project are. Basically they follow as:
1. Open code base
2. A website (can be the github README.md)
3. A releases/distributions area
4. A means of communication with the community (as simple as the issues page on github, but can be more in depth (e.g. email lists, slack, etc. )

I think those 4 things are the fundamental makeup of an OpenSource software project.

**Comment by chtompki** [comment]
Scratch the `/patterns/1-initial` I'll just make another `.md` file in the root of the project

**Comment by chtompki** [comment]
PR #182

**Comment by spier** [comment]
@chtompki @MaineC closing this issue for the time being, as it looks to be stale.

However you mentioned a "paper about open source ideas".
Did you end up writing this paper, and if yes, would you still want to pursue the idea of writing up key elements of that paper as a pattern?
