### ISSUE TITLE
Health

### ISSUE THREAD

**Issue by Ciampi10** [InnerSourceCommons/InnerSourcePatterns#183]

**Comment by spier** [comment]
Hi @Ciampi10. I am just seeing this issue now.

Just the title "Health" does not really tell me what this about :)
Could you elaborate please?

**Comment by spier** [comment]
@lenucksi I would suggest to close this request, as it was likely opened by mistake. @Ciampi10 can always open a new issue if the request/question is still relevant.

**Comment by lenucksi** [comment]
> 
> 
> @lenucksi I would suggest to close this request, as it was likely opened by mistake. @Ciampi10 can always open a new issue if the request/question is still relevant.

Fully agree here @spier, closing this.
