### ISSUE TITLE
Adapt PR labels to new contribution process

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#187]
We have defined [new pattern maturity levels](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/contributor-handbook.md#maturity-levels) as part of the new contribution process.

To make these maturity levels part of our shared language, and to institutionalize our new process, we want to remove the old labels on PRs that we don't use anymore. See https://github.com/InnerSourceCommons/InnerSourcePatterns/pulls

## What to do specifically

- remove the labels `0-Incomplete`, `1 - Do 1st Review`, and `5-Accepted`
- rename `A-Donut` to `1-Initial`
- rename `B-Unproven` to `2-structured`
- rename `C-Proven` to `3-validated`

## Side Note 

Only an Admin of this repo can do this work!

**Comment by spier** [comment]
@maxcapraro can you confirm that these were the label changes that you had in mind?

**Comment by spier** [comment]
@lenucksi with Max short on time right now, could you help to clean up these old labels as suggested above? I think they are only confusing  right now, as they don't fit our new Maturity Levels anymore. Thanks for your help!

**Comment by lenucksi** [comment]
Moved those. What about `2 - Needs revision` `3 - do second review` and `4 - finalize` looks like those should also be removed.

**Comment by spier** [comment]
@lenucksi great catch. Those three can be removed as well. I don't think we are using them right now anyways. We can always introduce new ones if we need them later.

Thanks!

**Comment by lenucksi** [comment]
Cleaned the remaining unused labels up, this concludes this issue. Closing it.

**Comment by spier** [comment]
Awesome, thank you!
