### ISSUE TITLE
Level up RFC pattern to Structured

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#215]
The pattern [Transparent Cross-Team Decision Making using RFCs](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/1-initial/transparent-cross-team-decision-making-using-rfcs.md) is currently in maturity **Initial**. We submitted this pattern rather quickly, to have it in the repo in time for the ISC Fall Summit 2020.

We have some further content available that is related to this pattern. Let's use that content to level up the pattern to maturity **Structured**:

- content from @tsadler1988's fantastic ISC Fall Summit 2020 presentation (see [video](https://www.youtube.com/watch?v=U6zlghE0HcE&list=PLCH-i0B0otNQZQt_QzGR9Il_kE4C6cQRy&index=15&t=4s))
- add a known instance to the pattern
- feedback from @MaineC [from the first PR](https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/204#pullrequestreview-485754276)

@tsadler1988 do you want to take the first stab at working in your content from the summit? Feel free to edit the existing content pretty broadly, as I wouldn't be surprized if my descriptions in the current pattern are not representing your approach correctly.

If you have time, you can also review @MaineC's feedback (see link above). If not, I am also happy to do that in a later PR.

Does this approach work for you?

**Comment by tsadler1988** [comment]
Sorry it's taken me so long to make time for this - finally raised #245 as a starting point.

**Comment by spier** [comment]
The linked PR is merged now, and the pattern is in Level 2-Structured now.
So let's close this issue 🎉 

Some ideas for future improvements of the pattern are kept in https://github.com/InnerSourceCommons/InnerSourcePatterns/issues/276.
