### ISSUE TITLE
Basic spell checker for patterns

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#218]
Patterns written straight in markdown format often have some minor spelling mistakes, as GitHub does not provide any automatic checks for that.

Therefore the patterns (and the book that we want to produce) would benefit from at least a basic spell check. That spell check could e.g. run when a PR is created. The spell checker should not make the CI run fail. I would rather use the results of the spell checker as recommendations to the author that they can decide to use, or not.

I found one spell checker at https://norvig.com/spell-correct.html but I am sure there are many.

**Comment by lenucksi** [comment]
Added the [prosebot](https://github.com/apps/prosebot) to our repo. It should become active on PRs for .md and .txt now. 
There are three linters active I can envision that we might reduce them to the spellchecker only.

**Comment by spier** [comment]
Nice nice nice. Looking forward to seeing the bot in action.

Feel free to close this issue already if you consider it solved (we can open it again if we want to do more at a later point).

**Comment by lenucksi** [comment]
> 
> 
> Nice nice nice. Looking forward to seeing the bot in action.
> 
> Feel free to close this issue already if you consider it solved (we can open it again if we want to do more at a later point).

I'll close once I've seen that it works.

**Comment by spier** [comment]
@lenucksi I just remembered prosebot, and that you added it. However in the last PRs that I created I did not see the bot interact with my PRs or anything. Do you know how it is supposed to work?

**Comment by lenucksi** [comment]
Looks we're either holding it wrong or it doesn't work at least as I expected. It 's installed according to its documentation and should just show up in PRs. Take a look at the linked docs above.

**Comment by dterol23** [comment]
I use in some other projects this spell checker GitHub action https://github.com/uribench/spell-check, not sure if that could also be interesting for this issue. My colleague (uribench at GitHub), wrote the spell checker and he will be happy to support the evaluation and integration if it is interesting. It can be downloaded and run locally first for testing. https://github.com/uribench/spell-check/blob/master/README.md

**Comment by spier** [comment]
@lenucksi not sure what changed but now prosebot is doing stuff. I see these 3 flavors of it on some PRs now.

![Screen Shot 2021-01-17 at 10 42 57 ](https://user-images.githubusercontent.com/163029/104836832-01590900-58b1-11eb-95f9-ee332a21acdb.JPG)

**Comment by spier** [comment]
We deactivated prosebot again today, as it was a bit too chatty. It created so many inline annotations in PRs that it became hard to read the actual pattern content or follow the feedback from other contributors. For an example of that see https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/289/files

Seems like it is hard to find a good tradeoff between too much and too little checking.

**Comment by spier** [comment]
Found this spellcheck acton today. Might be worth trying to see if it gives us more configurable options.
https://github.com/bagder/uncurled/blob/main/spellcheck.yaml

**Comment by spier** [comment]
🚀 we have a style & spell checker now!
