### ISSUE TITLE
Nicer domain for the book

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#250]
Currently the URLs of our InnerSourcePatterns book look like this:

* book landing page at [innersourcecommons.gitbook.io/innersource-patterns](https://innersourcecommons.gitbook.io/innersource-patterns/.)
* individual patterns at [innersourcecommons.gitbook.io/innersource-patterns/patterns/innersource-portal](https://innersourcecommons.gitbook.io/innersource-patterns/patterns/innersource-portal)

gitbook does allow us to configure a [Custom Domain](https://docs.gitbook.com/hosting/custom-domains).

A custom domain could look like this:

If we configure `books.innersourcecommons.org`, then the URLS would change like this:

* book landing page at `books.innersourcecommons.org/innersource-patterns`
* individual patterns at `books.innersourcecommons.org/innersource-patterns/patterns/innersource-portal`

While the URLs in this proposal are not much shorter than the current URLs, the approach would have some advantages:

* SEO for innersourcecommons.org (all keywords in our patterns drive traffic to innersourcecommons.org)
* more clear affiliation of the InnerSourcePatterns book with the InnerSource Commons
* the approach is extendable with new books? e.g. say we wanted to port https://dicortazar.gitbook.io/managing-inner-source-projects/, this would get the URL `books.innersourcecommons.org/managing-inner-source-projects`

Things that I don't like about the new URLs (somewhat unrelated to the custom domain topic actually):

* `books.innersourcecommons.org/innersource-patterns/patterns/innersource-portal` contains `patterns` too often :) We could potentially move all pattern files one level up so that the URLs would be `books.innersourcecommons.org/innersource-patterns/innersource-portal` instead.

What do people thing? Other ideas for a custom domains?

**Comment by spier** [comment]
I reviewed gitbook's configuration options for [custom domains](https://docs.gitbook.com/hosting/custom-domains) again.

If I understand the instruction's correctly, then gitbook offers theres 2 general options:

a) a sub-domain just for the patterns book (called **space domain**)

* book landing page at `patterns.innersourcecommons.org`
* individual patterns at `patterns.innersourcecommons.org/patterns/innersource-portal`

Note: I believe that in this configuration the project-id, "innersource-patterns" in our case, won't be part of the URL.

b) a sub-domain for all books that we host in our gitbook organization (called **organizational domain**)

* book landing page at `books.innersourcecommons.org/innersource-patterns`
* individual patterns at `books.innersourcecommons.org/innersource-patterns/patterns/innersource-portal`

**Comment by markdav-is** [comment]
I like this option: book landing page at patterns.innersource.org as it's self-contained and folks can easily see the main org as well.  seems the cleanest to me.  If you make more books, they can each have a specific prefix.

**Comment by spier** [comment]
Thanks for the feedback @markdav-is! I just realized that I got the domain part wrong in my previous comment (fixed now).

So it would be `patterns.innersourcecommons.org`. Still, short enough I think.

If I may pick your brain on yet another "URL question":
Which of these two URLs for an individual pattern would you prefer?

1. `patterns.innersourcecommons.org/patterns/innersource-portal`
2. `patterns.innersourcecommons.org/p/innersource-portal`

I am thinking that it would be nice to not repeat the term `pattern`. So I am leaning to option (2).
But maybe having `pattern` in the path as well it is actually better for SEO purposes? Not sure :)

**Comment by voborgus** [comment]
I will choose the third option if it's possible technically:
`patterns.innersourcecommons.org/innersource-portal` :)

another point to discuss here: since we're going to a subdomain is it possible to change the design of the git book? 
Not for 100% same with the website but at least copy colors and the header.

**Comment by spier** [comment]
Thanks for the feedback @voborgus .

> I will choose the third option if it's possible technically:
> `patterns.innersourcecommons.org/innersource-portal` :)

Can you elaborate why this would be your preferred version? Brevity of the URL, or something else?

It would be possible to do this. However it would require us to move all patterns directly into the root of the book, which means that they would be sitting side by side with the **Introduction** and the **Table of Contents**. Also if we want to add further pages to the book in the future that aren't patterns, there wouldn't be a natural place for those. For those reasons the patterns are in their own group at the moment.


> another point to discuss here: since we're going to a subdomain is it possible to change the design of the git book?
> Not for 100% same with the website but at least copy colors and the header.

Would you mind moving the design topic to a separate issue, so that we can keep this issue here focused on the domain?

**Comment by voborgus** [comment]
> Can you elaborate why this would be your preferred version? Brevity of the URL, or something else?

Yep and the meaning of the URL: `go to patterns subdomain and get the pattern with the name specified`

But I prefer the easiest possible way to fulfill the task and the short version with `/p/` works for me too.

**Comment by spier** [comment]
I am reaching out to @cewilliams about this. Will go for `patterns.innersourcecommons.org` as a sub-domain.
We can then test later how exactly we want the full URL (incl path) to look like.

**Comment by spier** [comment]
This is fully implemented now. Closing.
