### ISSUE TITLE
Adding Revision History section to pattern template

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#269]
Idea: how about we add a _Revision History_ section, @spier , @lenucksi ? 
I feel it's kinda odd to have more than one entry in the _Status_ section. Just my 0.02 $.

_Originally posted by @gruetter in https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/254#discussion_r554127296_

**Comment by lenucksi** [comment]
Sounds good to me, we'll need that ( + changelog and addressability) for a regular release of the "book" or website anyway.

How do we go at it?
A simple 
0.x for 1-initials
2.x for 2-structured
3.x for our highest grade?

counted in the footer? Would be great to be able to parse around a bit.
