### ISSUE TITLE
New pattern around Source Code Inventory

### ISSUE THREAD

**Issue by dterol23** [InnerSourceCommons/InnerSourcePatterns#310]
_Problem statement_: software, in particular source code as key company asset, is managed at enterprises with less care and rigorousness than other IT hardware inventories which diminishes the opportunities to maximize business value and control liability cost

_Thesis_: An unambiguous, complete, inexpensive, up-to-date, actionable inventory of Enterprise's source code repositories would be used it to identify and support potential valuable InnerSource assets

**Comment by dterol23** [comment]
@spier I am planning to start working on this following our past conversations. I've started with the pattern template but I thought it might be good to share is as an issue to gain visibility and see if others are interested.

**Comment by spier** [comment]
That's awesome @dterol23. If you like you can even post this ticket in the slack channel also, to see if other people have thought about this problem space in the context of InnerSource.

**Comment by spier** [comment]
This pattern is now live at https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/1-initial/source-code-inventory.md. Great job @dterol23, and thanks for sharing this approach with the community.

I hope (and expect actually) that many companies are using this or a similar strategy.
