### ISSUE TITLE
Core Team Pattern - Improvement Ideas

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#346]
These are improvement ideas for the [Core Team](https://patterns.innersourcecommons.org/p/core-team) pattern, as first discussed in https://github.com/InnerSourceCommons/InnerSourcePatterns/issues/345#issuecomment-906262562.

Hopefully the thread on this issue won't grow out of control, as multiple things are mentioned here. If it does, we can still split up this issue later.

## Improvement Ideas

1. Where in the [mindmap](https://patterns.innersourcecommons.org/explore-patterns) should we add the Core Team pattern? => The suggestion was `Technical Challenges` or `Organizational Challenges`. We can even add the pattern to both places in the mindmap.
2. Is there any visual that would support this pattern? Using any visuals/pictures/charts in the book makes it a lot prettier but of course we don't want to add a picture just for beauty-sake, it should also support the understandability of the pattern.
3. The pattern contains a reference to the Trusted Committer concept, which currently points to the respective [Learning Path segments](https://innersourcecommons.org/learn/learning-path/trusted-committer/) about the Trusted Committer. We also have a [pattern](https://patterns.innersourcecommons.org/p/trusted-committer) about the Trusted Committer, and it would be great to get that cross-reference added to the Core Team Pattern as well, so that readers can more easily find their way from one pattern to the other.

**Comment by spier** [comment]
@rrrutledge I am exploring visualization ideas. Curious to hear what you think. You should be able to comment and edit in the file:
https://docs.google.com/presentation/d/11JOByEO9QXlRLXX5BIv9rjUzPzCKErZzknD1OLcprQQ/edit#slide=id.p

**Comment by rrrutledge** [comment]
Great!  I will take a look this week sometime.

**Comment by rrrutledge** [comment]
1.  Sounds good.
2.  Added a rough idea at a  visualization.

![image](https://user-images.githubusercontent.com/9609562/131502100-954896e1-823a-42fd-9393-eaef7ded4f42.png)

3.  Sounds good.

**Comment by spier** [comment]
@rrrutledge I took your proposal and added some colors and stuff.
What do you think?

![core-team-visual](https://user-images.githubusercontent.com/163029/131666697-ccf1658e-9a25-44c6-a147-ac0ea2079932.png)

**Comment by rrrutledge** [comment]
It looks great, and I think would be a value add for this pattern.  I'm glad that you brought it up.

Looking at the graphic again, I think it would be good to slide down the "Feature" boxes so that there is an equal amount of space between them and the top "Core" box as the other "Core" boxes have between one another.  This spacing makes it clear that the features are built on top of core and avoids suggesting that the features are somehow separated from the core.

![image](https://user-images.githubusercontent.com/9609562/131676531-e43f59c9-054b-4c47-bb96-f60f6ae820c6.png)

**Comment by spier** [comment]
Thanks for the feedback. That makes perfect sense.

Will adapt that and then add it to PR #347 for you to review.
