### ISSUE TITLE
pattern/limited-management-support

### ISSUE THREAD

**Issue by nyeates** [InnerSourceCommons/InnerSourcePatterns#35]
There is engineering-level support of innersource, but not management-level. Ex: Management wont support sharing of source code across departments/contractors and still expects waterfall-type reporting of man-hr requirements (vs something more Agile).

**Comment by spier** [comment]
Playing devils advocate here :)
Given that this issue did not see any traction in 3 years, maybe we close it and wait for it to be reinvented if it is important?

**Comment by spier** [comment]
Not enough context in this issue to create a pattern from it. Will close it as **Stale**.

Also if this is truly an InnerSource pattern, I would expect it to be discovered one day by somebody else again :)
