### ISSUE TITLE
pattern/separate-contractors-wont-collaborate

### ISSUE THREAD

**Issue by nyeates** [InnerSourceCommons/InnerSourcePatterns#36]
Contractors from separate companies or organizations will not fully collaborate on a shared code-base, often viewing each other as competitive in nature despite an overarching org telling them otherwise. This is common in the US Federal Government, where the government is required to contract out the majority of its software production needs, and very often uses multiple contractors on a single project. It could also occur if org's have announced a partnership, but parties within each org still consider themselves competing forces.

**Comment by spier** [comment]
Playing devils advocate here :)
Given that this issue did not see any traction in 3 years, maybe we close it and wait for it to be reinvented if it is important?

**Comment by spier** [comment]
Not enough context in this issue to create a pattern from it. Will close it as **Stale**.

Also if this is truly an InnerSource pattern, I would expect it to be discovered one day by somebody else again :)
