### ISSUE TITLE
InnerSourceCommons as home for repository activity score implementations

### ISSUE THREAD

**Issue by 3cpt** [InnerSourceCommons/InnerSourcePatterns#366]
Hi all. 
I am implementing the [Repository Activity Score algorithm in Python](https://github.com/3cpt/repo-score-py/blob/main/src/repo_score/score.py), and I was thinking if it makes sense to create the repository inside `InnerSourceCommons` organization.

With this, the ownership - repo and package registry - it's part of the `InnerSourceCommons`. I can be maintainer, add other implementations - JavaScript (copy/paste from documentation), Go and C# - and take care of the publishing to package registry.

Tagging @spier. In part related to #341

**Comment by spier** [comment]
Just quickly letting you know that I have seen this @3cpt.
Great to hear that you will be implementing the activity score.

Keeping the code within the umbrella of the InnerSource Commons is an interesting idea for sure.
Let me check with other members of the InnerSource Commons what they think about this.

**Comment by spier** [comment]
@3cpt I just took a look at your `repo-score-py` repo.

If we add these implementations to the InnerSourceCommons org, was your idea to have a single repo that contains sub-folders for the different languages?

e.g. repo: `https://github.com/InnerSourceCommons/repo-activity-score`
with folders
```
├── python
├── go
├── javascript
├── csharp
├── ruby
└── etc
```

**Comment by 3cpt** [comment]
@spier looks good to me. 

It simplifies some integration test that could be done between multiple languages.
My only concern is about packaging using Actions for the different package registries.

**Comment by spier** [comment]
In which language will you actually use the activity score calculator yourself? I am assuming that you are putting an InnerSource Portal or similar together, in which you will be using the score?

Is it Python (as that's the implementation that you already have)?

I am wondering about this as we could potentially port your existing python repo into the InnerSourceCommons org, and then add to the README that we motivate other community members to contribute their own implementations, once they build them.

That would reduce some of the burden for you to build/test all of these implementations yourself.

**Comment by 3cpt** [comment]
I'm implementing it in Python because I want to use it in my personal project [(recorrente)](https://github.com/3cpt/recorrente), also I want to integrate in https://github.com/zkoppert/innersource-crawler/issues/17 because of the InnerSource Portal.
And I have plans to use it in an internal metric system, but probably in JavaScript - that is just copy & paste from the pattern page.

Your idea about porting seem good to me.

In the future, we can check if we can in any way to have a Github Action with multiple "publishers".

**Comment by spier** [comment]
Sounds good @3cpt. 
So let's move the repo over to the InnerSourceCommons, and try how that works out for this project.

Would you mind renaming your repo to `repo-activity-score` before the transfer?
That makes it more clear what the score is about (activity), and leaves us more breathing room to add implementations for other languages to the repo later.

For the transfer itself you have something like this:
- go to https://github.com/3cpt/repo-score-py/settings
- at the very bottom you find "Transfer ownership"
- type InnerSourceCommons
- confirm

Let me know when you are done, as likely one of the Owners of the InnerSourceCommons org will have to accept the transfer.

After that I can help you with adding things like README, License, etc.

**Comment by spier** [comment]
I am just reading up on how to [transfer repos](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#repository-transfers-and-organizations):
> To transfer repositories to an organization, you must have repository creation permissions in the receiving organization.

So likely what I proposed above will not work (but please try it).

If it doesn't work as described above, we can still get it done like this:
- transfer the repo to me (@spier)
- I will transfer it into the org (InnerSoureCommons) - I have repo creation permissions
- I will give you Admin permissions on the repo, so that we can collaborate

I think this approach will be easier than getting you "repo creation permissions" in the InnerSoureCommons org.

**Comment by 3cpt** [comment]
> Repository transfer to spier requested

I hope that the process occurs without problems. I already used Transfer sometimes, and the behavior sometimes is discussible.

**Comment by 3cpt** [comment]
@spier, thinking and preparing the next steps. What about PyPi (or other package registry)? The ISC has an account?
I need that someone with power to it add a Secret to the repo with a [PyPi](https://pypi.org/) API token. Example: `PYPI_TOKEN`.

Also, for something more synchronous, you can contact me in the ISC Slack - `@andre`

**Comment by spier** [comment]
Status: Repo migrated to https://github.com/InnerSourceCommons/repo-activity-score
Now setting up permissions and all for @3cpt.

I will close this issue here once I am done with the permissions.

**Comment by spier** [comment]
Setup is done. Work on this topic is continuing in repo https://github.com/InnerSourceCommons/repo-activity-score
