### ISSUE TITLE
pattern/hiring-leverages-culture

### ISSUE THREAD

**Issue by nyeates** [InnerSourceCommons/InnerSourcePatterns#37]
Human Resources department or hiring managers can use inner source and open source as a selling point to prospective candidates. These can be key to building and sustaining your target culture.

Mentioning it as "Inner Source (Internal Open Source)" may clarify to candidates who aren't familiar with the term. Also, mentioning full-out open source projects (if they exist in your org) may be 'sexy' to candidates.

**Comment by gruetter** [comment]
From my own experience of talking to friends who work in tech outside of my company, InnerSource and especially our flavour of _permissionless innovation_ was highly attractive. It also changed the perception of my company (not exactly a startup anymore). I think there's definitively a pattern in here.

I'm not so sure about the working title, though. How about _Cultural-change-through-hiring_ or something along these lines?

**Comment by nyeates** [comment]
Good to hear reinforcement. Ill move forward with it at some point and think of alternate titles - neither ring to me now (a few weeks later).

**Comment by spier** [comment]
Playing devils advocate here :)
Given that this issue did not see any traction in 3 years, maybe we close it and wait for it to be reinvented if it is important?

**Comment by spier** [comment]
I closed the associated PR, and linked to this issue from the pattern itself.
So if somebody wants to look up how the pattern was created, they can.
Closing this issue.
