### ISSUE TITLE
pattern/change-the-developers-mindset

### ISSUE THREAD

**Issue by dicortazar** [InnerSourceCommons/InnerSourcePatterns#39]
This task aims at bringing to this repo the donut available at https://github.com/paypal/InnerSourceCommons/wiki/Pattern:-change-the-developers-mindset

I'll assign this to myself in a first stage and upload the pull request.

**Comment by dicortazar** [comment]
Adding @NewMexicoKid as contributor of this donut.

https://github.com/paypal/InnerSourcePatterns/blob/pattern/change-developers-mindset/change-developers-mindset.md

**Comment by dicortazar** [comment]
@NewMexicoKid I'd like to work a bit more in the donut and then pull request our updates.

In addition, I remember I had to add another participant, but do not exactly remember who. Perhaps @kevinger ?

**Comment by nyeates** [comment]
I take it that this is here as a reminder for you. Thats fine. Just FYI that I will start clearing other issues related to tracking particular patterns. We wont normally do that here in issues any longer. I had done it as a test at one point.

**Comment by nyeates** [comment]
Arrgh. Maybe I am jumping the gun here (speaking too early). I think we should rid of the requirement to make an issue before all pattern additions. It may be useful when you dont have much info, such as a very quick donut /idea. But then once you have more than a few sentances, such as in this case, it becomes duplicate to what will be in the PR. Thoughts? Do Issues provide something I am missing? Seems like complexity to be required.... of course though, people can use them if they wish, especially to remind themselves or for small ideas.

**Comment by nyeates** [comment]
@dicortazar or @NewMexicoKid Please make a PR for the existing [branch that has 1 commit](https://github.com/paypal/InnerSourcePatterns/tree/pattern/change-developers-mindset), then close this Issue.

You will be able to add new commits and comments to that same branch/PR.

**Comment by dicortazar** [comment]
Ok, I'll produce a PR, thanks @nyeates

**Comment by dicortazar** [comment]
Closing this issue as suggested by  @nyeates . I've added @NewMexicoKid as reviewer in that PR.

Anyone interested, please feel free to add yourself to the PR.
