### ISSUE TITLE
Pattern-States.md created and updated

### ISSUE THREAD

**Issue by nyeates** [InnerSourceCommons/InnerSourcePatterns#44]
bring from wiki and then make it more detailed, explaining terms and states

**Comment by nyeates** [comment]
Created this file, pulled over from the wiki on this commit: https://github.com/paypal/InnerSourcePatterns/commit/2ee8cce5ea1646998f489b39e70304d14abefda3

However, it needs updating. Need to talk about all of the states, and in more depth.

**Comment by spier** [comment]
@nyeates the file you are linking to above looks like an early version of what we now have in `meta/pattern-states.md`.

Can this issue here be closed?
