### ISSUE TITLE
Add Metrics for Employee Satisfaction and Retention

### ISSUE THREAD

**Issue by Trueblueaddie** [InnerSourceCommons/InnerSourcePatterns#451]
https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/abd1635a828b694cc51e615c004356203ddce3be/patterns/1-initial/introducing-metrics-in-innersource.md?plain=1#L65

| Employee satisfaction & talent retention | eNPS score <br> attrition rate |

**Comment by spier** [comment]
Thanks for adding this suggestion @Trueblueaddie. Much appreciated.

Are you comfortable with making this change directly via a Pull Request?
e.g. by [editing the file](https://github.com/InnerSourceCommons/InnerSourcePatterns/edit/main/patterns/1-initial/introducing-metrics-in-innersource.md) as desired, and then committing your change and opening a new pull request with that change. 

Then we can point the authors to your PR and they can review it.

**Comment by spier** [comment]
Implemented in #455. Thank you!
