### ISSUE TITLE
Review and improve our documentation for first-time contributors

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#464]
We want to make it even easier for first-time contributors to improve our patterns collection in this repo.

Therefore it would be fantastic if you could review either of the documentation below that we have created for first-time contributors. If you find anything confusing, missing, or plain wrong, please send a PR with ideas for improvements.

## Resources to review

- main [README.md](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/README.md) of this repo
- [CONTRIBUTING.md](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/CONTRIBUTING.md)
- [Contributor Handbook](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/meta/contributor-handbook.md)

You don't have to review all of these! If you just have time to review one of them, that is a great contribution already!

**Comment by Mercysticks** [comment]
assign it to me please.

**Comment by spier** [comment]
@Mercysticks happy to!

Please note that these docs would benefit from review by multiple people, so I will accept PRs/reviews/improvements from more than one person.

**Comment by Mercysticks** [comment]
Okay

**Comment by subashpaul** [comment]
Created README for Hacktoberfest PR #467

**Comment by Mercysticks** [comment]
Made a few changes and created a PR @spier

**Comment by spier** [comment]
As hacktoberfest is over, let's consider this done.
