### ISSUE TITLE
Fix description of office hours

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#469]
I noticed that the description of our office hours is wrong.
https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/CONTRIBUTING.md#how-to-get-in-touch

We are not actually doing these any more, at least not in the European timezone.
So I would opt for just removing the description of the office hours.

**Comment by spier** [comment]
@mishari what's your take on this? Do you still do the office hours in your timezone?

**Comment by mishari** [comment]
I've not for a while now. I could start if there's interest, but after several months there doesn't seem to be?

**Comment by spier** [comment]
I see. I think I will remove the mention of the office hour from the docs then. We can always restart them in the future if we like.
