### ISSUE TITLE
:construction: Get "Extensions to Manage Contributions at Scale" published in our book

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#487]
_WIP: I am drafting this issue to describe the work required to level up a given pattern from Initial (Level 1) to Structured (Level 2). I am using the "Extensions to Manage Contributions at Scale" pattern as an example for this. I am hoping that later we can extract generalizable points into a GitHub issue template, that we can use whenever we want to do such "leveling up" for other patterns._

## Meta

* Pattern: [Extensions to Manage Contributions at Scale](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/patterns/1-initial/extensions-to-manage-contributions-at-scale.md)
* Previous PR: https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/444

## Goal

Improve the given pattern to get it published in our InnerSource patterns online book at [patterns.innersourcecommons.org](https://patterns.innersourcecommons.org).

Once published in the book, the pattern can be discovered more easily by people looking to improve their InnerSource practices. The upside for pattern authors and their orgs is an increased brand recognition, and positioning themselves as an InnerSource thought leader.

## Getting Started

* We recommend that you review the [Structured (L2) Requirements][] to understand the quality expectations we have set for the patterns in our book.
* Double check if there were any open discussion points in previous PRs about this pattern. You might built on these discussion points to improve the pattern further.

## Possible Improvements

Here some examples of possible activities that might improve this pattern:

* Since publishing this pattern as Initial, did you make any new experiences while applying this pattern?
* The current title isn't super long. Just a bit maybe :) Once we have published the pattern in the book it becomes harder to change the title (and filename) without breaking URLs. Therefore we recommend to take another look at title and file name. For further tips see [Naming Patterns][].
* Are there any other L2/Structured patterns that you could link to from within this pattern?
* Are there any resources that you could link to that would help to either validate your pattern, or make it easier for the readers to understand it? Please confirm that these are resources that you trust.
* Determine to which phase of the [InnerSource Program Mind Map][] the pattern should be added to (add it to at least one phase). This makes it easier for readers to discover your pattern as well.
* (optional) Do you know any other organizations using this pattern? Getting them to contribute their knowledge to the pattern and adding them as a **Known Instance** significantly hardens the pattern. Activities around this can also happen in a new issue/PR.

The above are just some suggestions.

You are the expert on your pattern, so please make your own judgement calls about how your pattern can be improved.

[Structured (L2) Requirements]: https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/meta/contributor-handbook.md#requirements-level-2---structured
[Naming Patterns]: https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/meta/pattern-style-guide.md#naming-patterns
[InnerSource Program Mind Map]: https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/pattern-categorization/README.md

**Comment by spier** [comment]
@Ssukriti we would love to get your pattern published in our online book. For that you find a couple of suggestions above of how the pattern could be improved. 

_Aside:_ We are planning to do this same exercise with some other pattern contributors shortly. Therefore any feedback you can give us about this process could help to make this simpler/faster for other contributors. Thank you!

**Comment by Ssukriti** [comment]
thank you for creating these guidelines, yes we will work on maturing the pattern in next few days. Do you have a timeline in mind @spier  by when it needs to make it in for next publication of the online book?

**Comment by spier** [comment]
@Ssukriti we don't have a fixed timeline, as we can publish the updates to our online book continuously.
Would be great to get it in before the end of the year though, also as another mini celebration of IBM's great contributions to InnerSource this year.

**Comment by Ssukriti** [comment]
@spier the PR is ready for review. 

1. We have updated title to a shorter one
2. Addressed open comments from earlier - have added a story section and architecture diagram
3. I could not find any other pattern to link to from within ours, but have referenced some wikipedia content as needed
4. We do not have new experiences on applying the pattern yet, but we can make a future update in next 6 months if we have more learnings to share.
5. We have determined the phase of mindmap  =   **scale** -> (new category) Technical challenges -> Difficult to maintain with large scale -> our pattern. Let me know when I should open that PR to mindmap, its probably after the pattern is moved to structured?

Once the PR is reviewed, please let me know if I should be opening another PR to move it to structured folder or will that be done by the reviewers?

**Comment by spier** [comment]
The pattern was published to our book now through PR https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/512

So this is all done 🥳

**Comment by Ssukriti** [comment]
Thank you so much for your support and assistance @spier

**Comment by spier** [comment]
It was my pleasure. I learned a lot from your approach!
