### ISSUE TITLE
Japanese patterns in gitbook don't get indexed by Google

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#490]
The [Japanese translations](https://patterns.innersourcecommons.org/v/ja/) of our patterns are not indexed by Google.

As we host the content using gitbook, we suspect it is related to that.

The gitbook [SEO documentation](https://docs.gitbook.com/tour/seo) describes that they create a sitemap automatically. 

On closer inspection it turns out the links for the Japanese content in the generated [sitemap.xml](https://patterns.innersourcecommons.org/sitemap.xml) wrong. 
They contain a double slash, where it should just be one slash. e.g. `https://patterns.innersourcecommons.org//v/ja/toc`.
When trying to open that link you get a "Page not found".

Curl says:
```
$ curl -S "https://patterns.innersourcecommons.org//v/ja/toc"
<a href="/ssr-render/patterns.innersourcecommons.org/v/ja/toc?cacheBust=1669375787795">Moved Permanently</a>.
```

That might be the reason why google does not index those pages.

## Aside: 

The same issue exists on the gitbook used for [jp-contents](https://github.com/InnerSourceCommons/jp-contents).

**Comment by spier** [comment]
I just sent a Support request to gitbook.

**Comment by yuhattor** [comment]
I appreciate it!

**Comment by yuhattor** [comment]
Thanks, it looks now the resources are successfully crawled and pages are shown in the result.
I think it's time to close this PR:)

@spier 
I appreciate your support! Sitemap was also fixed!

![image](https://user-images.githubusercontent.com/15963767/217755828-eb5dc096-b1de-440a-bf0d-4b65eabb2a28.png)

**Comment by spier** [comment]
@yuhattor thanks for double checking this. Great to hear that gitbook fixed this on their end!

I will also let them know that this is fixed via the Support request that I had previously opened. I assume they will be glad to hear that we are a happy customer again :)
