### ISSUE TITLE
🚧 Get "Standard Release Process and Published Artifacts" published in our book

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourcePatterns#491]
_WIP: I am drafting this issue to describe the work required to level up a given pattern from Initial (Level 1) to Structured (Level 2). I am using the "Extensions to Manage Contributions at Scale" pattern as an example for this. I am hoping that later we can extract generalizable points into a GitHub issue template, that we can use whenever we want to do such "leveling up" for other patterns._

## Meta

* Pattern: [Standard Release Process and Published Artifacts](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/patterns/1-initial/release-process.md)
* Previous PR: #332 

## Goal

Improve the given pattern to get it published in our InnerSource patterns online book at [patterns.innersourcecommons.org](https://patterns.innersourcecommons.org).

Once published in the book, the pattern can be discovered more easily by people looking to improve their InnerSource practices. The upside for pattern authors and their orgs is an increased brand recognition, and positioning themselves as an InnerSource thought leader.

## Getting Started

* We recommend that you review the [Structured (L2) Requirements][] to understand the quality expectations we have set for the patterns in our book.
* Double check if there were any open discussion points in previous PRs about this pattern. You might built on these discussion points to improve the pattern further.

## Possible Improvements

Here some examples of possible activities that might improve this pattern:

- [ ] The **Context** section doesn't contain the type of content that the [pattern template](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/meta/pattern-template.md#context) asks for, yet. The two sections **Context** and **Forces** are often the hardest to write for new pattern authors, so we would be more than happy to help you to improve this section.
- [ ] Since publishing this pattern as Initial, did you make any new experiences while applying this pattern?
- [ ] Are there any other authors from within your org that you would like to get involved?
- [x] The current title isn't super long. Just a bit maybe :) Once we have published the pattern in the book it becomes harder to change the title (and filename) without breaking URLs. Therefore we recommend to take another look at title and file name. For further tips see [Naming Patterns][].
- [x] Are there any other L2/Structured patterns that you could link to from within this pattern?
- [ ] Are there any resources that you could link to that would help to either validate your pattern, or make it easier for the readers to understand it? Please confirm that these are resources that you trust.
- [x] Determine to which phase of the [InnerSource Program Mind Map][] the pattern should be added to (add it to at least one phase). This makes it easier for readers to discover your pattern as well.
- [ ] (optional) Do you know any other organizations using this pattern? Getting them to contribute their knowledge to the pattern and adding them as a **Known Instance** significantly hardens the pattern. Activities around this can also happen in a new issue/PR.

The above are just some suggestions.

You are the expert on your pattern, so please make your own judgement calls about how your pattern can be improved.

[Structured (L2) Requirements]: https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/meta/contributor-handbook.md#requirements-level-2---structured
[Naming Patterns]: https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/meta/pattern-style-guide.md#naming-patterns
[InnerSource Program Mind Map]: https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/pattern-categorization/README.md

**Comment by spier** [comment]
@dgrizzanti we would love to get your pattern published in our online book. For that you find a couple of suggestions above of how the pattern could be improved.

_Aside:_ We are planning to do this same exercise with some other pattern contributors shortly. Therefore any feedback you can give us about this process could help to make this simpler/faster for other contributors. Thank you!

**Comment by dgrizzanti** [comment]
hey @spier - that sounds great, thanks for reaching out! Let me review and see what would need to be updated as it's been a while since I've looked at this.

**Comment by spier** [comment]
I just thought that the release notes are also a great opportunity to [praise participants](https://patterns.innersourcecommons.org/p/praise-participants), especially if those are InnerSource contributions from another team!
