### ISSUE TITLE
Extend Standard Base Documentation pattern adding a Code of Conduct template

### ISSUE THREAD

**Issue by rmarting** [InnerSourceCommons/InnerSourcePatterns#555]
Building an Inner Source community requires create a safe space of collaboration, communication and work. This space should be bounded with a set of rules, standards, and responsabilities. This kind of things are usually defined in a Code of Conduct.

Defining a Code of Conduct within an InnerSource project is essential for fostering a welcoming and inclusive community environment. It sets clear expectations for behavior and establishes guidelines that promote respectful and collaborative interactions among project contributors. A well-crafted Code of Conduct helps prevent and address issues such as harassment, discrimination, and toxic behavior, ensuring that everyone feels safe and valued within the project. By providing a framework for positive and inclusive participation, a Code of Conduct encourages diverse perspectives, enhances collaboration, and ultimately leads to the development of higher-quality open-source software.

It is very common to have a `CODE_OF_CONDUCT.md` file as part of the repository of an InnerSource project, so it could be usefull to extend the Standar Base Documentation pattern including a reference about this file, its goals, and adding a template.

A good template can be an adapted version of the Code of Conduct provided by the [Contributor Covenant](https://www.contributor-covenant.org/), a very extended used by many communities and projects.

This issue is opened with the goal to extend the Standar Base Documentation pattern adding some references, and a template of a Code of Conduct. That it will help new InnerSource projects to accelerate the adoption, and promoting the collaboration with their communities.

**Comment by rmarting** [comment]
This issue was created to extend the Standard Base Documentation pattern to add some templates to cover the Code of Conduct (`CODE_OF_CONDUCT.md`), however, we moved to define a new patter to describe it instead of to update the original pattern.

Now, the Code of Conduct pattern is part of the communitiy with the initial status... So, I am wondering if we should close this issue and the original PR.

@spier I think, this issue is no longer needed, as the original PR. Do you think that it is a good idea to close them? It could help to sanitize the current list of issues and PR. What do you think?

**Comment by spier** [comment]
@rmarting thanks for catching this. Sounds like a good idea :) I am doing this now.
