### ISSUE TITLE
[Pattern Idea] Broadening Contributor Pool

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourcePatterns#645]
Working with @Trueblueaddie to kick-start a new proposed pattern. 

## Title

Title TBD

## Patlet

GitHub can be intimidating to non-tech contributors. In this case, an organization wanted to engage large numbers of tech and non-tech contributors, in diverse roles, dispersed across the globe.

The solution was to create a neutral space so that no matter what the skill level or tech experience, input was taken and given to the tech team to incorporate into the InnerSource project.

## Problem

What is the problem - crisp definition of the problem.
Short description, usually not more than a couple sentences, that describes what the issues and challenges are.
Be careful not to morph into information found in other sections below.

## Story (optional)

Sometimes there is a story that helps people understand the pattern better.

## Context

Where does the problem exist?
What are the pre-conditions?
**Unchangeable** before the solution goes into place.
The content here is often tied to the applicability of the pattern for other readers: "Do I have this same particular situation?"

## Forces

What makes the problem difficult?
What are the trade-offs?
These are constraints that **can be changed** at a cost.
The solution might change one or more of these forces in order to solve the problem, while also in-turn changing the context.

## Sketch (optional)

visual illustration

## Solutions

Verified resolutions and possible resolutions to the problem.

## Resulting Context

What is the situation after the problem has been solved?
The original context is changed indirectly by way of the solution.
Often this section can include discussion of the next possible Patterns/problems introduced.
This section can be short in content - the solution may not introduce new problems or change much context.

## Rationale (optional)

Explains why this is the right solution; using totally different words WHY this solution balances these forces and this context to solve this problem.
Can expand on what-if's or theories.

## Known Instances (optional)

Where has this been seen before?
Helps to reinforce that this is a REAL pattern and that you match the context.

May mention:

* A particular business
* Anonymized instances ex: "3 companies have proven that this is a good solution" or "A large financial services org...".

## Status (optional until merging)

General pattern status is stored in GitHub's Label tagging - see any pull request.
Note that this GitHub label tagging becomes less visible once the pattern is finalized and merged, so having some information in this field is helpful.

You might store other related info here, such as review history: "Three of us reviewed this on 2/5/17 and it needs John's expertise before it can go further."

## Author(s) (optional)

Often, this is yourself.
If you need to, find someone in the InnerSource Commons to be the nominal author (As Told To).
Could also be no-one if you do not want to take on authorship (common with a donut looking for a solution).

## Acknowledgments (optional)

Include those who assisted in helping with this pattern - both for attribution and for possible future follow up.
Though optional, most patterns should list who helped in their creation.

## Alias (optional)

If this pattern is also known under a different name than what is listed unter **Title**, please list those alternative titles here.
e.g. if the pattern is named after the problem it solves, a helpful alias might be one that describes the solution that is applied.

**Comment by claredillon** [comment]
@Trueblueaddie is going to elaborate on this pattern. I don't have permission to assign it to her - but perhaps someone else does

**Comment by spier** [comment]
@claredillon would you be ok to use a temporary title, instead of "TBD"? That would make it easier to find this pattern again.

How about "Lower technical barriers" for the time being?

**Comment by claredillon** [comment]
> @claredillon would you be ok to use a temporary title, instead of "TBD"? That would make it easier to find this pattern again.
> 
> How about "Lower technical barriers" for the time being?

Will do - though "Broadening contributor pool" may fit better...  @Trueblueaddie you can let us know if you think of something that fits better.

**Comment by spier** [comment]
@claredillon @Trueblueaddie this pattern idea is in this state for almost a year now (yes, time flies).

Therefore I am wondering if you still want to follow this idea, or drop it for the time being?

In an effort to clean up our repo a bit, I am already closing this issue.
However if you leave a comment here, we can open it again straight away.
