### ISSUE TITLE
bug: CODEOWNERS file has errors

### ISSUE THREAD

**Issue by jmeridth** [InnerSourceCommons/InnerSourcePatterns#669]
Looks like @psanxiao needs write access to fix [`.github/CODEOWNERS`](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/.github/CODEOWNERS)

<img width="432" alt="Screenshot 2024-03-24 at 7 52 40 AM" src="https://github.com/InnerSourceCommons/InnerSourcePatterns/assets/35014/a5a34136-d1bc-485b-a4a4-019ce1e73b5b">

<img width="649" alt="Screenshot 2024-03-24 at 7 52 47 AM" src="https://github.com/InnerSourceCommons/InnerSourcePatterns/assets/35014/f08fbef1-81a6-4f8d-b095-427bb5d90aab">

**Comment by spier** [comment]
Fair point @jmeridth. it is nice of you (and GitHub :)) to remind us of this!

If I recall correctly, our idea with the lower section of the CODEOWNERS file was, that those folks doing the translation work might sort of be "maintainer apprentice", and through their involvement in the project become maintainers eventually. I think this is why we might not have given all of them WRITE access immediately.

However I think there is no harm in doing so. Therefore I just sent an invite to @psanxiao, so if he accepts this issue will disappear shortly.

Let's keep this issue open until we confirmed that it is fixed ❤️

**Comment by jmeridth** [comment]
I love that re: maintainer apprentice. Thank you for clarifying. No worries if you want to close this. I appreciate the process. 

😆 emoji is re `(and GitHub :))` in your message.

**Comment by jmeridth** [comment]
@spier Could this "maintainer apprentice" approach be another pattern to add to this book? 🤔 

That could definitely be something organizations could use to vet maintainers.

**Comment by spier** [comment]
Hmm. That is an interesting idea.

We don't have a pattern about this, I think. 

I wonder if this has been expressed under different names elsewhere already. Maybe even just as a part of a description of how to onboard a new maintainer. Wouldn't be too far fetched to assume that a new maintainer might get increasing responsibilities (and with that permissions) in stages of increasing difficulty and risk.

However my suspicion is that in open source the general idea would be to start with a lot of trust right from the beginning, while many orgs with an InnerSource might be more risk adverse in the same situation. Just speculating :)

If you are interested in this space and have time, would be great to break this out into a new issue and research this a bit.

**Comment by jmeridth** [comment]
<img src="https://media3.giphy.com/media/QKkV58ufpV4ksJ1Okh/giphy-downsized-medium.gif"/>

**Comment by jmeridth** [comment]
@spier with the invite sent to @psanxiao, I'm good closing this issue.  Thank you for the great conversation on the "maintainer apprentice" pattern.

**Comment by jmeridth** [comment]
@spier https://github.com/InnerSourceCommons/InnerSourcePatterns/issues/670
