### ISSUE TITLE
Improve Grammar, Nomenclature, and Link Updates in the InnerSource Patterns book

### ISSUE THREAD

**Issue by agostontorok** [InnerSourceCommons/InnerSourcePatterns#719]
# Issue Description:

We are seeking contributors to help enhance the readability and accuracy of chapters of the [InnerSource Patterns Book](https://github.com/InnerSourceCommons/InnerSourcePatterns). This effort is part of [Hacktoberfest](https://hacktoberfest.com/), an initiative to encourage participation in open source projects. Beginners are especially welcome! This task involves checking for grammar and typographical errors, ensuring the consistency of terminology used throughout one (!) chapter, and verifying that all hyperlinks are functional and up-to-date.

# Goals:
- Grammar and Typo Checks: Review the chapter for any grammatical errors and typos. This includes but is not limited to punctuation, capitalization, verb tense, and sentence structure.
- Consistency of Nomenclature: Ensure that all terminology and jargon are used consistently throughout the chapter. For example, if "InnerSource" is capitalized in one section, it should be capitalized throughout.
- Update Not Working Links: Check all hyperlinks within the chapter to ensure they are not broken. Replace any outdated or non-working links with the correct URLs.

# Instructions for Contributors:

- Fork the Repository: Start by forking the repository to your GitHub account.
- Clone the Repository: Clone the forked repository to your local machine.
- Make Your Changes: As you read through the chapter of your choice, make edits to correct grammar, ensure terminology consistency, and update broken links.
- Commit Changes: Commit your changes with a clear commit message, e.g., "Fix typos in Chapter 5", "Standardize terminology in Chapter 5", or "Update broken links in Chapter 5".
- Push Changes: Push your changes to your forked repository on GitHub.
- Create a Pull Request: Submit a pull request from your fork to the original ISC book repository. Make sure to describe what changes you've made and why.
- Wait for Review: Your pull request will be reviewed by maintainers, who may suggest further modifications or merge your changes.

# Helpful Resources:
[GitHub Forking and Cloning Guide](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)
[Markdown Syntax Guide](https://www.markdownguide.org/basic-syntax/)
[Understanding Pull Requests](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests)

# Getting Help:
If you need help with this task, please feel free to reach out on our community Discord channel or comment directly on this issue. We're happy to assist newcomers!

# Note:
This task is beginner-friendly and a great way to learn about contributing to open-source projects, particularly in the realm of technical writing and documentation. We appreciate your contributions to making ISC resources more accessible and accurate!

**Comment by dhirajs16** [comment]
Hey @spier, is the grammatical error issue in Chapter 5 still valid? If so, assign me the issue so I can resolve it.

**Comment by spier** [comment]
> Hey @spier, is the grammatical error issue in Chapter 5 still valid? If so, assign me the issue so I can resolve it.

Come again @dhirajs16? Which chapter 5 are you referring to? Can you share a link to what you mean, so that there are no misunderstandings?

**Comment by spier** [comment]
@agostontorok as hacktoberfest is over, I hope it is ok to close this issue?
