### ISSUE TITLE
File for "Poor Naming Conventions" is missing

### ISSUE THREAD

**Issue by ChristianKurz** [InnerSourceCommons/InnerSourcePatterns#97]
The link to [Poor Naming Conventions](https://github.com/paypal/InnerSourcePatterns/blob/master/poor-naming-conventions.md) 404s and i can't find the file to correct the link.

**Comment by StingRayZA** [comment]
@NewMexicoKid Thanks for merging - would you mind resolving this issue?

**Comment by NewMexicoKid** [comment]
Fixed by @StingRayZA
